// GENERATED FILE — DO NOT EDIT
// Run `scripts/mix.sh grappa.gen_wire_types` to regenerate.
// Source: lib/grappa/**/*wire.ex + GrappaWeb.AuthJSON + GrappaWeb.BootJSON + GrappaWeb.ErrorTokens + GrappaWeb.MeJSON
// === External types (referenced by Wire modules) ===
export const ADMISSION_FLOW = [
    "login_fresh",
    "login_existing",
    "bootstrap_user",
    "bootstrap_visitor",
    "patch_network_connect",
    "visitor_reconnect",
    "admin_credential_bind",
];
export const CHANNEL_DIRECTORY_STATUS = ["fresh", "stale", "empty", "refreshing"];
export const IRCAUTH_FSMAUTH_METHOD = [
    "auto",
    "sasl",
    "server_pass",
    "nickserv_identify",
    "none",
];
export const IRCIDENTIFIER_CASEMAPPING = ["ascii", "rfc1459", "rfc1459_strict"];
export const LIVE_INTROSPECTION_SESSION_ENTRY_DEGRADED_FIELD = [
    "joined_channels",
    "peer_address",
];
export const NETWORKS_CREDENTIAL_CONNECTION_STATE = [
    "connected",
    "failing",
    "parked",
    "failed",
];
export const NETWORKS_CREDENTIAL_GENDER = ["male", "female", "nonbinary"];
export const NETWORKS_NETWORK_SERVICES_FLAVOR = ["azzurra", "atheme", "oftc", "unknown"];
export const SCROLLBACK_MESSAGE_KIND = [
    "privmsg",
    "notice",
    "action",
    "join",
    "part",
    "quit",
    "nick_change",
    "mode",
    "topic",
    "kick",
    "server_event",
];
export const SCROLLBACK_META_TKEY = [
    "target",
    "new_nick",
    "modes",
    "args",
    "numeric",
    "severity",
    "who",
    "who_target",
    "names",
    "names_target",
    "raw_verb",
    "raw_sender",
    "raw_params",
    "sender_user",
    "sender_host",
    "sender_prefix",
    "sender_kind",
    "ctcp_verb",
    "ctcp_args",
    "ctcp_target",
    "notice_target",
    "statusmsg",
    "nick_fallback",
    "link_failure",
];
export const SESSION_WINDOW_STATE_WINDOW_STATE = [
    "pending",
    "invited",
    "joined",
    "failed",
    "kicked",
    "parked",
];
export const SESSION_LOG_EVENT = [
    "connected",
    "registered",
    "identified",
    "deidentified",
    "disconnected",
    "backoff",
    "nick_changed",
];
export const THEMES_TOKEN_MODEL_FONT_FAMILY = [
    "mono-default",
    "jetbrains-mono",
    "fira-code",
    "iosevka",
    "hack",
    "cascadia-code",
    "source-code-pro",
    "ibm-plex-mono",
];
export const THEMES_TOKEN_MODEL_SIZE_MODE = ["cover", "repeat"];
export const WINDOW_COUNTS_SEVERITY = ["mention", "message", "event", "none"];
// === Grappa.AdminEvents.Wire ===
export const ADMIN_EVENTS_WIRE_EVENT_KIND = [
    "circuit_open",
    "circuit_close",
    "capacity_reject",
    "visitor_deleted",
    "visitor_reaped",
    "visitor_share_token_minted",
    "user_share_token_minted",
    "reaper_swept",
    "upload_reaped",
    "uploads_swept",
    "session_disconnected",
    "session_terminated",
    "network_caps_updated",
    "circuit_reset",
    "cap_counts_changed",
    "user_created",
    "user_updated",
    "user_password_changed",
    "user_deleted",
    "network_created",
    "network_deleted",
    "server_added",
    "server_updated",
    "server_removed",
    "credential_bound",
    "credential_updated",
    "credential_unbound",
    "login_throttled",
    "web_session_severed",
];
export const ADMIN_EVENTS_WIRE_LOGIN_THROTTLE_DOOR = [
    "mode1_login",
    "visitor_login",
    "totp_login",
    "passkey_recovery",
    "passkey_login_options",
    "share_token_consume",
    "oidc_login",
];
export const ADMIN_EVENTS_WIRE_LOGIN_THROTTLE_SCOPE = ["ip", "ip_account"];
export const NETWORKS_CREDENTIALS_ADMIN_WIRE_SESSION_ACTION = [
    "left_alone",
    "stopped",
    "spawned",
    "not_spawned",
];
export const NETWORKS_CREDENTIALS_ADMIN_WIRE_SPAWN_ERROR = [
    "resolve_failed",
    "not_found",
    "ip_cap_exceeded",
    "visitor_cap_exceeded",
    "user_cap_exceeded",
    "network_circuit_open",
    "start_failed",
];
// === Grappa.Session.Wire ===
export const SESSION_WIRE_WIRE_EVENT_KIND = [
    "channels_changed",
    "own_nick_changed",
    "isupport_changed",
    "umode_changed",
    "session_identity_changed",
    "supported_umodes_changed",
    "topic_changed",
    "channel_modes_changed",
    "channel_created",
    "members_seeded",
    "names_reply",
    "who_reply",
    "server_reply",
    "joined",
    "window_pending",
    "window_invited",
    "window_invite_declined",
    "join_failed",
    "kicked",
    "away_confirmed",
    "mentions_bundle",
    "whois_bundle",
    "whois_avatar_ready",
    "peer_away",
    "invite_ack",
    "lusers_bundle",
    "whowas_bundle",
    "banlist_bundle",
    "links_bundle",
    "directory_progress",
    "directory_complete",
    "directory_failed",
    "connection_progress",
    "recover_progress",
    "recover_result",
    "presence_changed",
    "presence_error",
    "presence_snapshot",
];
export const SESSION_WIRE_SERVER_REPLY_SOURCE = ["info", "version", "motd", "admin"];
export const SESSION_WIRE_RECOVER_STEP = [
    "identify",
    "register",
    "nick",
    "recover",
    "release",
];
export const SESSION_WIRE_RECOVER_STATUS = ["running", "ok", "failed"];
export const SESSION_WIRE_RECOVER_REASON = [
    "wrong_password",
    "nick_unavailable",
    "services_declined",
    "identify_unconfirmed",
];
export const SESSION_WIRE_RECOVER_OUTCOME = ["succeeded", "failed"];
// === GrappaWeb.ErrorTokens ===
export const ERROR_TOKENS_SHARED_ERROR_TOKEN = [
    "not_found",
    "forbidden",
    "invalid_line",
    "body_too_large",
];
export const ERROR_TOKENS_REST_ERROR_TOKEN = [
    ...ERROR_TOKENS_SHARED_ERROR_TOKEN,
    "bad_request",
    "unauthorized",
    "nickserv_pass_retired",
    "file_too_large",
    "metadata_strip_failed",
    "insufficient_storage",
    "unsupported_media_type",
    "invalid_setting",
    "addressing_unusable",
    "rate_limited",
    "too_many_attempts",
    "theme_cap_reached",
    "list_full",
    "invalid_mask",
    "not_raster",
    "too_large",
    "ssrf_blocked",
    "fetch_failed",
    "image_reencode_failed",
    "not_connected",
    "forbidden_vhost",
    "client_token_scope",
    "client_token_cap_reached",
    "invalid_credentials",
    "invalid_two_factor",
    "two_factor_challenge_expired",
    "already_enabled",
    "too_many_sessions",
    "network_busy",
    "network_unreachable",
    "captcha_required",
    "captcha_failed",
    "service_degraded",
    "db_unavailable",
    "malformed_nick",
    "malformed_ident",
    "password_required",
    "passkey_required",
    "passkey_not_configured",
    "password_mismatch",
    "network_not_visitor_enabled",
    "network_ambiguous",
    "network_unconfigured",
    "upstream_unreachable",
    "connect_timeout",
    "welcome_timeout",
    "session_timeout",
    "probe_timeout",
    "internal",
    "session_plan_resolve_failed",
    "contract_migrations_pending",
    "duplicate_migration_versions",
    "stale_code_path",
    "invalid_message",
    "anon_collision",
    "nick_in_use",
    "cannot_disconnect_self",
    "source_not_local",
    "already_exists",
    "already_attached",
    "credentials_present",
    "scrollback_present",
    "last_admin",
    "share_token_expired",
    "share_token_consumed",
    "not_invited",
    "validation_failed",
];
export const ERROR_TOKENS_CHANNEL_ERROR_TOKEN = [
    ...ERROR_TOKENS_SHARED_ERROR_TOKEN,
    "unknown_topic",
    "invalid_payload",
    "user_not_found",
    "network_not_found",
    "no_session",
    "not_explicit",
    "invalid_nick",
    "not_cached",
    "lookup_failed",
    "open_failed",
    "close_failed",
    "unknown_event",
    "save_failed",
    "invalid_reason",
    "invalid_mask",
    "upstream_unavailable",
    "persist_failed",
    "invalid_channel",
    "links_in_flight",
    "unsupported_list_mode",
    "nothing_to_recover",
    "already_identified",
    "recovery_in_progress",
    "rate_limited",
];
